---
version: '3.2'
services:
  ilias-db:
    image: mariadb:11.1
    container_name: ilias-db
    restart: unless-stopped
    command:
      --character-set-server=utf8
      --collation-server=utf8_general_ci
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/docker/data/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  ilias-app:
    image: sturai/ilias:latest
    container_name: ilias-app
    restart: unless-stopped
    depends_on:
      - ilias-db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/docker/data/ilias/html:/var/www/html/data
      - /var/docker/data/ilias/data:/var/iliasdata/ilias
    environment:
      - ILIAS_AUTO_SETUP=1
      - ILIAS_DB_HOST=ilias-db
      - ILIAS_DB_NAME=${MYSQL_DATABASE}
      - ILIAS_DB_USER=${MYSQL_USER}
      - ILIAS_DB_PASSWORD=${MYSQL_PASSWORD}
      - ILIAS_ROOT_PASSWORD=  #  Starkes Passwort setzen!
      - ILIAS_SETUP_PASSWORD=  #  Starkes Passwort setzen!
      - ILIAS_CLIENT_NAME=default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ilias.entrypoints=websecure"
      - "traefik.http.routers.ilias.rule=Host(`${ILIAS_URL}`)"  # Domain anpassen
      - "traefik.http.routers.ilias.tls=true"
      - "traefik.http.routers.ilias.tls.certresolver=default"
      - "traefik.http.routers.ilias.middlewares=secHeaders@file"
      - "traefik.http.services.ilias.loadbalancer.server.port=80"
    networks:
      - default
      - traefik_proxy

  ilias-server:
    image: sturai/ilias-ilserver:latest
    container_name: ilias-server
    restart: unless-stopped
    depends_on:
      - ilias-app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/docker/data/ilias/lucened:/var/lucenedata/ilias
      - /var/docker/data/ilias/html:/app/data:ro
      - /var/docker/data/ilias/data:/app/iliasdata:ro
    networks:
      - default

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
