---
version: '3.3'

services:
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/docker/portainer:/data
    labels:
      - "traefik.backend=portainer"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:portainer.example.com" # URL entsprechend anpassen!
      - "traefik.port=9000"
      - "traefik.docker.network=traefik_proxy"
    restart: always
    networks:
      - traefik_proxy
      - default

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge