---
version: '3'

services:
  influxdb:
    image: influxdb:2.3
    container_name: influxdb
    restart: unless-stopped
    volumes:
      - /var/docker/influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
